name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Pyinstaller
      run: |
        pip3 install -U setuptools wheel
        pip3 install pyinstaller
    - name: Build Python executable
      run: python3 -O -m PyInstaller -y -F sibnet.py 
    - name: Commit changes
      run: |        
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout -b release
        git add .
        git commit -m "Build executable" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GIT_TOKEN }}
        branch: release
